name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOMAIN: https://loremipsum.com
      PROXY: lorempisum.com
    steps:
      - uses: actions/checkout@v3
      - name: Setup .env
        run: |
          echo "DOMAIN=${{ env.DOMAIN }}" >> .env
          echo "PROXY=${{ env.PROXY }}" >> .env
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
